[http.routers]
  [http.routers.web-router]
    rule = "PathPrefix(`/`)"
    service = "web-service"
    priority = 1

  [http.routers.api-router]
    rule = "PathPrefix(`/api`)"
    service = "api-service"
    middlewares = ["api-prefix"]
    priority = 2

[http.middlewares]
  [http.middlewares.api-prefix.stripPrefix]
    prefixes = ["/api"]
    forceSlash = true

[http.services]
  [http.services.web-service.loadBalancer]
    [[http.services.web-service.loadBalancer.servers]]
      url = "http://127.0.0.1:6060"
  [http.services.api-service.loadBalancer]
    [[http.services.api-service.loadBalancer.servers]]
      url = "http://127.0.0.1:3000"
